# Generated by Django 6.0.2 on 2026-02-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('symptom_type', models.CharField(choices=[('GI', 'Gastrointestinal (Diarrhea, Vomiting)'), ('NEURO', 'Neurological (Dizziness, Seizures)'), ('DERM', 'Dermatological (Rashes, Itching)'), ('OTHER', 'Other')], max_length=10)),
                ('severity', models.IntegerField(default=1, help_text='1 (Mild) to 10 (Critical)')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SatelliteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='satellite_images/')),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('chlorophyll_index', models.FloatField(help_text='Detected chlorophyll percentage (0-100)')),
                ('turbidity_index', models.FloatField(help_text='Detected turbidity percentage (0-100)')),
                ('risk_score', models.FloatField(help_text='Calculated risk score (0-100)')),
                ('location_name', models.CharField(default='Unknown Location', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WaterSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ph', models.FloatField()),
                ('turbidity', models.FloatField()),
                ('temperature', models.FloatField()),
                ('dissolved_oxygen', models.FloatField()),
                ('conductivity', models.FloatField()),
            ],
        ),
    ]
